### ISSUE TITLE
Integration with lightline.vim

### ISSUE THREAD

**Issue by TaurusOlson** [soywod/vim-keepeye#7]
Hi,
It's good to see this vim plugin getting more and more and traction.
Could you please also integrate it with [lightline.vim](https://github.com/itchyny/lightline.vim) which is similar to [vim-airline](https://github.com/vim-airline/vim-airline)?

**Comment by soywod** [comment]
I'll check how do that. Thank you :)

**Comment by soywod** [comment]
It has been integrated :tada:

**Comment by TaurusOlson** [comment]
I've just tested it. Thanks a lot!
