### ISSUE TITLE
Use original message on the system notification

### ISSUE THREAD

**Issue by stsewd** [soywod/vim-keepeye#9]
Due to recent changes, the message on the notification is displayed with the fill spaces in front.

I think we can move this

https://github.com/soywod/vim-keepeye/blob/2bdaf2daf32335f1fcd423e6704a9f87b957b1f1/autoload/keepeye.vim#L6

to be calculated where is really needed.

**Comment by stsewd** [comment]
Actually looks like this is only needed for this step https://github.com/soywod/vim-keepeye/blob/2bdaf2daf32335f1fcd423e6704a9f87b957b1f1/autoload/keepeye.vim#L11

So we can pass g:keepeye_message to the other function

**Comment by soywod** [comment]
Which other function ? I'm not sure to get it. The full message is built in `keepeye#Callback()` method, and is needed by `keepeye#helper#TriggerSystemEvents` and `keepeye#helper#WithHighlightGroup`. Could you precise ?

**Comment by stsewd** [comment]
The message that is passed to `keepeye#helper#TriggerSystemEvents` and `keepeye#helper#WithHighlightGroup` results in 
```
                                 message
```
which doesn't look at all in the notification popup.

So, we can pass the original message to 

https://github.com/soywod/vim-keepeye/blob/2bdaf2daf32335f1fcd423e6704a9f87b957b1f1/autoload/keepeye.vim#L9

**Comment by soywod** [comment]
I understand now, I'm gonna check this soon :)

**Comment by soywod** [comment]
I've refactored this part :) thank you :tada:
